name: Docker Image CI
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'pyproject.toml'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout git
      uses: actions/checkout@v2

    - name: get current version
      id: version
      run: echo "::set-output name=version::$(sed -rn '/^version\s*=\s*\"([^\"]+)\"/{s//\1/p; q}' ./pyproject.toml)"
 
    - name: build & push docker image
      id: build
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        IMAGE_NAME=${GCR_REGISTRY}/${APP_NAME}
        TAG=${BRANCH_NAME}.${VERSION}
        LATEST_TAG=${BRANCH_NAME}.latest
        echo "::set-output name=tag::$TAG"
      env:
        APP_NAME: ${{ github.event.repository.name }}
        VERSION: ${{ steps.version.outputs.version }}

    - name: checkout gitops repo
      uses: actions/checkout@v2
      with:
        repository: buzzni-parker/gitops-test
        path: gitops-test
        token: ${{ secrets.TOKEN }}

    - name: file list
      run: ls

    - name: env list
      run: export

    - name: change deployment yaml
      uses: mikefarah/yq@v4.17.2
      with:
        cmd: yq eval -i '.xmas-fifth-day.turtle-doves = "github/action:$TAG"' 'gitops-test/test-dir/test.yaml'
      env:
        TAG: "${{ steps.build.outputs.tag }}"

    - name: cat yaml
      run: cat gitops-test/test-dir/test.yaml

    - name: merge branch
      uses: broadinstitute/datarepo-actions/actions/merger@0.59.0
      env:
        COMMIT_MESSAGE: "change deployment yaml: ${{ steps.build.outputs.tag }}"
        GITHUB_REPO: gitops-test
        SWITCH_DIRECTORIES: true
        MERGE_BRANCH: main
