name: Github Action CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'pyproject.toml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: set values
      id: value
      run: | 
        IMAGE_NAME=${GCR_REGISTRY}/${APP_NAME}
        VERSION=$(sed -rn '/^version\s*=\s*\"([^\"]+)\"/{s//\1/p; q}' ./pyproject.toml)
        BRANCH_NAME=${GITHUB_REF##*/}
        TAG=${BRANCH_NAME}.${VERSION}
        LATEST_TAG=${BRANCH_NAME}.latest

        echo "::set-output name=image::$IMAGE_NAME:$TAG"
        echo "::set-output name=latest-image::$IMAGE_NAME:$TAG"
        echo "::set-output name=gitops-name::gitops-test"
        echo "::set-output name=gitops-repo::$GITHUB_REPOSITORY_OWNER/gitops-test"

    - name: checkout git
      uses: actions/checkout@v2

    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    - name: checkout gitops repo
      uses: actions/checkout@v2
      with:
        repository: ${{ steps.value.outputs.gitops-repo }}
        path: ${{ steps.value.outputs.gitops-name }}
        token: ${{ secrets.TOKEN }}

    - name: change deployment yaml
      uses: mikefarah/yq@v4.17.2
      with:
        cmd: yq eval -i '.xmas-fifth-day.turtle-doves = env(IMAGE)' ${GITHUB_REPO}/test-dir/test.yaml
      env:
        GITHUB_REPO: ${{ steps.value.outputs.gitops-name }}
        IMAGE: ${{ steps.value.outputs.image }}

    - name: merge commit
      run: |
        cd "${GITHUB_WORKSPACE}"/"${GITHUB_REPO}"

        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config pull.rebase false
        git pull
        git add .
        git commit -m "${COMMIT_MESSAGE}"
        git push
        git rev-parse HEAD        
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_REPO: ${{ steps.value.outputs.gitops-name }}
